general.import = ["/home/sergio/.config/alacritty/toml/theme.toml", "/home/sergio/.config/alacritty/toml/font.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.99

[window.padding]
x = 2
y = 2
