[colors.bright]
black = "#d7d7d7"
blue = "#0031a9"
cyan = "#00538b"
green = "#005e00"
magenta = "#721045"
red = "#a60000"
white = "#000000"
yellow = "#813e00"

[colors.cursor]
cursor = "#505050"
text = "#000000"

[colors.normal]
black = "#e0e0e0"
blue = "#2544bb"
cyan = "#30517f"
green = "#315b00"
magenta = "#8f0075"
red = "#972500"
white = "#000000"
yellow = "#70480f"

[colors.primary]
background = "#eeeeee"
foreground = "#000000"

[colors.selection]
background = "#bcbcbc"
text = "#000000"

[env]
THEME = "modus-operandi"
THEME_IS_LIGHT = "1"
